Addressing Issue nb#2
Link-/gh-stars pull request #11
Opened 2024-01-01 19:40 UTC by knbr13

This PR addresses [issue nb#2](https://github.com/Link-/gh-stars/issues/2)

The changes are just as follows:
- create new variable to store the maximum width of the table.
- pass this variable to the `tableprinter.New` function, to create a table with custom width.
- add new flag to the root command, flag name: "table-max-width", flag shorthand name: "w".

2024-01-03 09:52 UTC, Link- commented
Thank you @knbr13! A few things before I merge this change:

- [ ] Add tests to cover this functionality 
- [ ] Update the title of this PR to describe exactly what's changed

2024-01-03 09:52 UTC, Link- requested changes
Thank you @knbr13! A few things before I merge this change:

- [ ] Add tests to cover this functionality 
- [ ] Update the title of this PR to describe exactly what's changed

2024-01-05 00:22 UTC, knbr13 commented
Hello @Link- 
Thanks for your response.

What do you mean by "Add tests to cover this functionality"?
What I did is just adding a new flag to make the table max width customizable by the user.
I used functionalities that is already tested.
I didn't come up with new logic.

2024-01-05 19:15 UTC, Link- commented
@knbr13 - in https://github.com/Link-/gh-stars/blob/6020a3c4f3eea2b619fccc9d883994254c9450f7/cmd/root_test.go#L310 add a new scenario that will take a new table width input and test the output of the render function against a @knbr13 - in https://github.com/Link-/gh-stars/blob/6020a3c4f3eea2b619fccc9d883994254c9450f7/cmd/root_test.go#L310 add a new scenario that will take a new table width input and test the output of the render function against a hard coded output. 

Anyway, not a big deal.

2024-01-05 19:15 UTC, Link- approved these changes

2024-01-05 19:16 UTC, merged